### ISSUE TITLE
choose license

### ISSUE THREAD

**Issue by agabrys** [countdowntimer/temp-backlog#9]

**Comment by agabrys** [comment]
@ivijan we can use:

* Apache 2.0: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
* BSD 2-Clause: https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)

I think Apache 2.0 is more user-friendly and also better protects the authors. If you agree, then I will create tasks in backlogs to add licenses :)

**Comment by agabrys** [comment]
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by ivijan** [comment]
I agree to go with Apache 2.0
